INFOPLIST_FILE=Info.plist
THEMEPLIST_FILE=Theme.plist
IBRICKR_PXL_PLIST=Package/iBrickr/PxlPkg.plist
SOURCES=\
	Sources/main.m \
	Sources/LumaQQ.m \
	Sources/Message/MessageHistory.m \
	Sources/Message/MessageManager.m \
	Sources/Message/MessageRipper.m \
	Sources/UI/UIBaseChat.m \
	Sources/UI/UIClusterChat.m \
	Sources/UI/UIController.m \
	Sources/UI/UIAccountManage.m \
	Sources/UI/UIAccountEdit.m \
	Sources/UI/UIChatLog.m \
	Sources/UI/UIClusterAuth.m \
	Sources/UI/UIClusterInfo.m \
	Sources/UI/UIClusterMessageSetting.m \
	Sources/UI/UIClusterOperation.m \
	Sources/UI/UIGroupOperation.m \
	Sources/UI/UILogin.m \
	Sources/UI/UIMain.m \
	Sources/UI/UINameEdit.m \
	Sources/UI/UIPreference.m \
	Sources/UI/UISelectHead.m \
	Sources/UI/UISelectValue.m \
	Sources/UI/UIUserAuth.m \
	Sources/UI/UIUserChat.m \
	Sources/UI/UIUserInfo.m \
	Sources/UI/UIUserOperation.m \
	Sources/UI/UIUtil.m \
	Sources/UI/DataSource/UserTableDataSource.m \
	Sources/UI/DataSource/ClusterTableDataSource.m \
	Sources/UI/DataSource/HistoryTableDataSource.m \
	Sources/UI/DataSource/MyselfTableDataSource.m \
	Sources/UI/DataSource/MessageTableDataSource.m \
	Sources/UI/DataSource/MoreTableDataSource.m \
	Sources/UI/DataSource/RecentTableDataSource.m \
	Sources/UI/DataSource/SearchTableDataSource.m \
	Sources/UI/View/AccountTable.m \
	Sources/UI/View/BubbleIMCell.m \
	Sources/UI/View/ChatLogIMCell.m \
	Sources/UI/View/ClusterCell.m \
	Sources/UI/View/ClusterIMCell.m \
	Sources/UI/View/ImageChooser.m \
	Sources/UI/View/GroupCell.m \
	Sources/UI/View/SystemIMCell.m \
	Sources/UI/View/UserCell.m \
	Sources/UI/View/UserIMCell.m \
	Sources/UI/View/PushButtonTableCell.m \
	Sources/UI/View/UISwipeDeleteTable.m \
	Sources/Core/QQClient.m \
	Sources/Core/Bean/AdvancedSearchedUser.m \
	Sources/Core/Bean/ClusterIM.m \
	Sources/Core/Bean/ClusterInfo.m \
	Sources/Core/Bean/ClusterMessageSetting.m \
	Sources/Core/Bean/ClusterNameCard.m \
	Sources/Core/Bean/ClusterNotification.m \
	Sources/Core/Bean/ContactInfo.m \
	Sources/Core/Bean/CustomHead.m \
	Sources/Core/Bean/FontStyle.m \
	Sources/Core/Bean/Friend.m \
	Sources/Core/Bean/FriendGroup.m \
	Sources/Core/Bean/FriendLevel.m \
	Sources/Core/Bean/FriendRemark.m \
	Sources/Core/Bean/FriendStatus.m \
	Sources/Core/Bean/FriendStatusChangedNotification.m \
	Sources/Core/Bean/LastTalkTime.m \
	Sources/Core/Bean/Member.m \
	Sources/Core/Bean/MobileIM.m \
	Sources/Core/Bean/NormalIM.m \
	Sources/Core/Bean/NormalIMHeader.m \
	Sources/Core/Bean/QQOrganization.m \
	Sources/Core/Bean/QQUser.m \
	Sources/Core/Bean/ReceivedIMPacketHeader.m \
	Sources/Core/Bean/SMSReply.m \
	Sources/Core/Bean/SearchedUser.m \
	Sources/Core/Bean/Signature.m \
	Sources/Core/Bean/SignatureChangedNotification.m \
	Sources/Core/Bean/SubCluster.m \
	Sources/Core/Bean/SystemIM.m \
	Sources/Core/Bean/TempSessionIM.m \
	Sources/Core/Bean/UserProperty.m \
	Sources/Core/Bean/Weather.m \
	Sources/Core/CustomHead/CustomHeadReceiver.m \
	Sources/Core/Event/AuxiliaryFamilyEventTrigger.m \
	Sources/Core/Event/BasicFamilyEventTrigger.m \
	Sources/Core/Event/EventRouter.m \
	Sources/Core/Event/QQNotification.m \
	Sources/Core/Event/QQNotificationCenter.m \
	Sources/Core/Event/StatusEvent.m \
	Sources/Core/Extension/NSData-Base64.m \
	Sources/Core/Extension/NSData-BytesOperation.m \
	Sources/Core/Extension/NSData-CRC32.m \
	Sources/Core/Extension/NSData-MD5.m \
	Sources/Core/Extension/NSData-QQCrypt.m \
	Sources/Core/Extension/NSMutableData-CustomAppending.m \
	Sources/Core/Extension/NSMutableData-Trim.m \
	Sources/Core/Extension/NSNumber-Serialization.m \
	Sources/Core/Extension/NSString-Converter.m \
	Sources/Core/Extension/NSString-Filter.m \
	Sources/Core/Extension/NSString-Validate.m \
	Sources/Core/Foundation/NSColor.m \
	Sources/Core/Foundation/NSFont.m \
	Sources/Core/Network/QQConnection.m \
	Sources/Core/Network/HttpInterceptor.m \
	Sources/Core/Network/Socks5Interceptor.m \
	Sources/Core/Packet/Packet.m \
	Sources/Core/Packet/InPacket.m \
	Sources/Core/Packet/OutPacket.m \
	Sources/Core/Packet/AuxiliaryInPacket.m \
	Sources/Core/Packet/AuxiliaryOutPacket.m \
	Sources/Core/Packet/BasicInPacket.m \
	Sources/Core/Packet/BasicOutPacket.m \
	Sources/Core/Packet/AuxiliaryConnectionAdvisor.m \
	Sources/Core/Packet/BasicConnectionAdvisor.m \
	Sources/Core/Packet/PacketParser.m \
	Sources/Core/Packet/AuxiliaryFamily/Incoming/GetCustomHeadDataReplyPacket.m \
	Sources/Core/Packet/AuxiliaryFamily/Incoming/GetCustomHeadInfoReplyPacket.m \
	Sources/Core/Packet/AuxiliaryFamily/Outcoming/GetCustomHeadDataPacket.m \
	Sources/Core/Packet/AuxiliaryFamily/Outcoming/GetCustomHeadInfoPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/AddFriendReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/AdvancedSearchUserReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/AuthInfoOpReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/AuthQuestionOpReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/AuthorizeReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/ChangeStatusReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/ClusterCommandReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/DeleteFriendReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/FriendDataOpReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/FriendStatusChangedPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/GetFriendGroupReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/GetFriendListReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/GetKeyReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/GetLoginTokenReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/GetOnlineOpReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/GetServerTokenReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/GetUserInfoReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/GroupDataOpReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/KeepAliveReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/LevelOpReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/LoginReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/ModifyInfoReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/PasswordVerifyReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/PrivacyOpReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/PropertyOpReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/ReceivedIMPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/RemoveSelfReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/SearchUserReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/SelectServerReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/SendIMReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/SendSMSReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/SignatureOpReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/SystemNotificationPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/TempSessionOpReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/UploadFriendGroupReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Incoming/WeatherOpReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/AddFriendPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/AdvancedSearchUserPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/AuthInfoOpPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/AuthQuestionOpPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/AuthorizePacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ChangeStatusPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterActivatePacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterAuthorizePacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterBatchGetCardPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterCommandPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterDismissPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterExitPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterGetCardPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterGetChannelSettingPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterGetInfoPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterGetLastTalkTimePacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterGetMemberInfoPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterGetMessageSettingPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterGetOnlineMemberPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterGetVersionIdPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterJoinPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterModifyCardPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterModifyChannelSettingPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterModifyInfoPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterModifyMemberPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterModifyMessageSettingPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterSearchPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterSendIMExPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterSetRolePacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterSubOpPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterTransferRolePacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ClusterUpdateOrganizationPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/DeleteFriendPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/FriendDataOpPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/GetFriendGroupPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/GetFriendListPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/GetKeyPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/GetLoginTokenPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/GetOnlineOpPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/GetServerTokenPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/GetUserInfoPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/GroupDataOpPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/KeepAlivePacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/LevelOpPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/LoginPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/LogoutPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ModifyInfoPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/PasswordVerifyPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/PrivacyOpPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/PropertyOpPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/ReceivedIMReplyPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/RemoveSelfPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/SearchUserPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/SelectServerPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/SendIMPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/SendSMSPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/SignatureOpPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/TempClusterActivatePacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/TempClusterCreatePacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/TempClusterExitPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/TempClusterGetInfoPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/TempClusterModifyInfoPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/TempClusterModifyMemberPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/TempClusterSendIMPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/TempSessionOpPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/UploadFriendGroupPacket.m \
	Sources/Core/Packet/BasicFamily/Outcoming/WeatherOpPacket.m \
	Sources/Core/Service/IMService.m \
	Sources/Core/Tool/ByteTool.m \
	Sources/Core/Tool/ByteBuffer.m \
	Sources/Core/Tool/SystemTool.m \
	Sources/Job/BaseJob.m \
	Sources/Job/GetClusterInfoJob.m \
	Sources/Job/GetMessageSettingJob.m \
	Sources/Job/GetClusterNameCardJob.m \
	Sources/Job/GetClusterVersionIdJob.m \
	Sources/Job/GetCustomHeadDataJob.m \
	Sources/Job/GetCustomHeadInfoJob.m \
	Sources/Job/GetFriendGroupJob.m \
	Sources/Job/GetFriendLevelJob.m \
	Sources/Job/GetMemberInfoJob.m \
	Sources/Job/GetOnlineMemberJob.m \
	Sources/Job/GetRemarkJob.m \
	Sources/Job/GetSignatureJob.m \
	Sources/Job/GetUserPropertyJob.m \
	Sources/Job/JobController.m \
	Sources/Job/UploadFriendGroupJob.m \
	Sources/Model/Cluster.m \
	Sources/Model/ClusterSpecificInfo.m \
	Sources/Model/Group.m \
	Sources/Model/GroupManager.m \
	Sources/Model/User.m \
	Sources/Tool/DefaultFace.m \
	Sources/Tool/FileTool.m \
	Sources/Tool/ImageTool.m \
	Sources/Tool/LocalizedStringTool.m \
	Sources/Tool/PreferenceTool.m \
	Sources/Tool/SoundTool.m \
	Sources/Tool/ThemeTool.m

CC=/usr/local/bin/arm-apple-darwin-gcc
CXX=/usr/local/bin/arm-apple-darwin-g++
CFLAGS=-fsigned-char -I$(SRCROOT)/Sources \
				-I$(SRCROOT)/Sources/Message \
				-I$(SRCROOT)/Sources/UI \
				-I$(SRCROOT)/Sources/UI/DataSource \
				-I$(SRCROOT)/Sources/UI/View \
				-I$(SRCROOT)/Sources/Core \
				-I$(SRCROOT)/Sources/Core/Bean \
				-I$(SRCROOT)/Sources/Core/CustomHead \
				-I$(SRCROOT)/Sources/Core/Event \
				-I$(SRCROOT)/Sources/Core/Extension \
				-I$(SRCROOT)/Sources/Core/Foundation \
				-I$(SRCROOT)/Sources/Core/Network \
				-I$(SRCROOT)/Sources/Core/Packet \
				-I$(SRCROOT)/Sources/Core/Packet/AuxiliaryFamily/Incoming \
				-I$(SRCROOT)/Sources/Core/Packet/AuxiliaryFamily/Outcoming \
				-I$(SRCROOT)/Sources/Core/Packet/BasicFamily/Incoming \
				-I$(SRCROOT)/Sources/Core/Packet/BasicFamily/Outcoming \
				-I$(SRCROOT)/Sources/Core/Service \
				-I$(SRCROOT)/Sources/Core/Tool \
				-I$(SRCROOT)/Sources/Job \
				-I$(SRCROOT)/Sources/Model \
				-I$(SRCROOT)/Sources/Tool
LDFLAGS=-Wl,-syslibroot,/usr/local/arm-apple-darwin/heavenly \
				-ObjC \
				-lobjc \
				-lcrypto \
				-liconv \
				-framework CoreFoundation \
				-framework Foundation \
				-framework UIKit \
				-framework LayerKit \
				-framework CoreGraphics \
				-framework GraphicsServices \
				-framework AudioToolbox \
				-framework MusicLibrary \
				-framework Message \
				-framework CFNetwork \
				-framework IOKit
LD=$(CC)

WRAPPER_NAME=$(PRODUCT_NAME).app
EXECUTABLE_NAME=$(PRODUCT_NAME)
SOURCES_ABS=$(addprefix $(SRCROOT)/,$(SOURCES))
INFOPLIST_ABS=$(addprefix $(SRCROOT)/,$(INFOPLIST_FILE))
THEMEPLIST_ABS=$(addprefix $(SRCROOT)/,$(THEMEPLIST_FILE))
OBJECTS=\
	$(patsubst %.c,%.o,$(filter %.c,$(SOURCES))) \
	$(patsubst %.cc,%.o,$(filter %.cc,$(SOURCES))) \
	$(patsubst %.cpp,%.o,$(filter %.cpp,$(SOURCES))) \
	$(patsubst %.m,%.o,$(filter %.m,$(SOURCES))) \
	$(patsubst %.mm,%.o,$(filter %.mm,$(SOURCES)))
OBJECTS_ABS=$(addprefix $(CONFIGURATION_TEMP_DIR)/,$(OBJECTS))
APP_ABS=$(BUILT_PRODUCTS_DIR)/$(WRAPPER_NAME)
PRODUCT_ABS=$(APP_ABS)/$(EXECUTABLE_NAME)
PXL_TEMP_DIR=$(BUILT_PRODUCTS_DIR)/$(PRODUCT_NAME)

all: $(PRODUCT_ABS)
	cp *.png $(APP_ABS)
	cp Images/*.png $(APP_ABS)
	cp Head/*.png $(APP_ABS)
	cp Face/*.png $(APP_ABS)
	mkdir -p $(APP_ABS)/English.lproj
	mkdir -p $(APP_ABS)/zh_CN.lproj
	cp English.lproj/*.strings $(APP_ABS)/English.lproj
	cp zh_CN.lproj/*.strings $(APP_ABS)/zh_CN.lproj
	mkdir -p $(APP_ABS)/Sound/QQ
	mkdir -p $(APP_ABS)/Sound/TM
	cp Sound/QQ/*.aif $(APP_ABS)/Sound/QQ
	cp Sound/TM/*.aif $(APP_ABS)/Sound/TM

$(PRODUCT_ABS): $(APP_ABS) $(OBJECTS_ABS)
	$(LD) $(LDFLAGS) -o $(PRODUCT_ABS) $(OBJECTS_ABS)

$(APP_ABS): $(INFOPLIST_ABS) $(THEMEPLIST_ABS)
	mkdir -p $(APP_ABS)
	cp $(INFOPLIST_ABS) $(APP_ABS)/
	cp $(THEMEPLIST_ABS) $(APP_ABS)/
	
$(CONFIGURATION_TEMP_DIR)/%.o: $(SRCROOT)/%.m
	mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@
	
pxl:
	mkdir -p $(PXL_TEMP_DIR)/app
	cp $(IBRICKR_PXL_PLIST) $(PXL_TEMP_DIR)
	cp icon.png $(PXL_TEMP_DIR)
	cp -R $(APP_ABS) $(PXL_TEMP_DIR)/app
	cd $(PXL_TEMP_DIR);zip -r ../LumaQQ4iPhone.pxl *
	rm -rf $(PXL_TEMP_DIR)
	
installer:
	mkdir -p $(PXL_TEMP_DIR)/app
	cp -R $(APP_ABS) $(PXL_TEMP_DIR)/app
	cd $(PXL_TEMP_DIR);zip -r ../LumaQQ4iPhone.zip *
	rm -rf $(PXL_TEMP_DIR)

clean:
	rm -f $(OBJECTS_ABS)
	rm -rf $(APP_ABS)

